### ISSUE TITLE
Submit Press Release

### ISSUE THREAD

**Issue by chesterAlmonte** [IbinexPH/cryptoearth#14]
https://custom-58hp.frb.io/cryptoearth/submit-press-release/
https://custom-58hp.frb.io/cryptoearth/contact-us/

![press-release](https://user-images.githubusercontent.com/37319302/39105706-f76c82ea-46e9-11e8-9660-8c6b5d70f2cd.png)

For Ipad Device

**Comment by ricky-cabugawan** [comment]
set min-width to 0
